<div class="container-xl col-sm-4">
    <form action="/admin/categories/store" method="post">
        <div class="form-group">
            <label for="cat_code">Category's code</label>
            <input type="text" class="form-control" id="cat_code" name="cat_code" placeholder="Enter Category's code">
        </div>
        <div class="form-group">
            <label for="cat_name">Category's name</label>
            <input type="text" class="form-control" id="cat_name" name="cat_name" placeholder="Enter Category's name" <?= if $catego ?> >
        </div>
        <button type="submit" class="btn btn-primary">Сохранить</button>
    </form>
</div>

