<div class="container-xl col-sm-4">
    <form action="/admin/categories/update" method="post">
        <?php foreach ($this->record as $item): ?>
        <div class="form-group">
            <label for="cat_code">Category's code</label>
            <input type="text" class="form-control" id="cat_code" name="cat_code" value="<?= $item['cat_code'] ?>" placeholder="Enter Category's code">
        </div>
        <div class="form-group">
            <label for="cat_name">Category's name</label>
            <input type="text" class="form-control" id="cat_name" name="cat_name" value="<?= $item['cat_name'] ?>" placeholder="Enter Category's name">
        </div>
        <div>
            <input type="text" name="cat_id" value="<?= $item['cat_id'] ?>" hidden>
        </div>
        <?php endforeach; ?>
        <button type="submit" class="btn btn-primary">Сохранить</button>
    </form>
</div>
