<div class="container col-sm-7">
    <div class="table-responsive ">
        <div class="table-wrapper">
            <div class="table-title">
                <div class="row">
                    <div class="col-sm-4">
                        <h2>Category <b>Management</b></h2>
                    </div>
                    <div class="col-sm-7">
                        <a href="#" class="btn btn-secondary"><i class="material-icons">&#xE147;</i> <span>Add New Category</span></a>
                    </div>
                </div>
            </div>

            <table class="table table-striped table-hover">

                <thead>
                <tr>
                    <th>#</th>
                    <th>Category's code</th>
                    <th>Category's name</th>
                    <th>Action</th>
                </tr>
                </thead>


                <tbody>
                <?php foreach ($this->categories as $category) : ?>
                    <tr>
                        <?php foreach ($category as $cat) : ?>
                            <td><?= $cat ?></td>
                        <?php endforeach; ?>
                        <td>
                            <a href="categories/update/<?= $category['cat_id'] ?>" class="settings" title="Settings"
                               data-toggle="tooltip"><i class="material-icons">&#xE8B8;</i></a>
                            <a href="categories/delete/<?= $category['cat_id'] ?>" class="delete" title="Delete"
                               data-toggle="tooltip"><i class="material-icons">&#xE5C9;</i></a>
                        </td>
                    </tr>

                <?php endforeach; ?>

                </tbody>
            </table>

        </div>

    </div>
</div>




