         <table class="table table-striped table-hover">

            <thead>
            <tr>
                <?php foreach (($this -> categories)[0] as $key => $category):?>
                <th><?= $key ?></th>
                <?php endforeach; ?>
                <th>Action</th>
            </tr>
            </thead>


            <tbody>
            <?php foreach ($this->categories as $category) :?>
            <tr>
                <?php foreach ($category as $cat) : ?>
                <td><?= $cat ?></td>
                <?php endforeach; ?>
                <td>
                    <a href="#" class="settings" title="Settings" data-toggle="tooltip"><i class="material-icons">&#xE8B8;</i></a>
                    <a href="categories/delete/<?= $category['cat_id']?>" class="delete" title="Delete" data-toggle="tooltip"><i class="material-icons">&#xE5C9;</i></a>
                </td>
            </tr>

            <?php endforeach; ?>

            </tbody>
        </table>


